schema_version = "1.0.0"

id ="UsdGameExporter"
version = "0.1.0"
name = "USD Game Exporter"
tagline = "A gamedev-oriented toolset for USD Workflows"
maintainer = "Jean-Silas Moor <jeansilas@wiselich.com>"
type = "add-on"

tags = ["Import-Export"]

blender_version_min =  "4.2.0"

license = [
  "SPDX:GPL-2.0-or-later",
]

platforms = ["windows-x64"]


[permissions]
files = "It's an I/O tool"
